# Generated by Django 3.0.3 on 2020-08-05 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.TextField()),
                ('Address2', models.TextField()),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=2)),
                ('Zip', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('TaxID', models.IntegerField(max_length=9)),
                ('Phone', models.IntegerField(max_length=10)),
                ('NAICS', models.IntegerField(max_length=5)),
                ('HasBeenProfitable', models.BooleanField()),
                ('HasBankruptedInLast7Years', models.BooleanField()),
                ('InceptionDate', models.DateTimeField()),
                ('Address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_apps.Address')),
            ],
        ),
    ]
