# Generated by Django 3.0.3 on 2020-08-05 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.TextField()),
                ('Address2', models.TextField()),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=2)),
                ('Zip', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('TaxID', models.IntegerField(max_length=9)),
                ('Phone', models.IntegerField(max_length=10)),
                ('NAICS', models.IntegerField(max_length=5)),
                ('HasBeenProfitable', models.BooleanField()),
                ('HasBankruptedInLast7Years', models.BooleanField()),
                ('InceptionDate', models.DateTimeField()),
                ('Address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_apps.Address')),
            ],
        ),
        migrations.CreateModel(
            name='CFApplicationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestedLoanAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('StatedCreditHistory', models.IntegerField()),
                ('LegalEntityType', models.CharField(max_length=50)),
                ('FilterID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFRequestID', models.IntegerField()),
                ('RequestDate', models.DateTimeField()),
                ('CFApiUserId', models.CharField(max_length=50)),
                ('CFApiPassword', models.CharField(max_length=50)),
                ('IsTestLead', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SelfReportedCashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnualRevenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('MonthlyAverageBankBalance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('MonthlyAverageCreditCardVolume', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('DateOfBirth', models.DateTimeField()),
                ('HomePhone', models.IntegerField()),
                ('SSN', models.IntegerField()),
                ('PercentageOfOwnership', models.IntegerField()),
                ('HomeAddress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_apps.Address')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_apps.Business')),
                ('CFApplicationData', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_apps.CFApplicationData')),
                ('Owners', models.ManyToManyField(to='loan_apps.Owner')),
                ('RequestHeader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_apps.RequestHeader')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='SelfReportedCashFlow',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan_apps.SelfReportedCashFlow'),
        ),
    ]
