# Generated by Django 3.0.3 on 2020-08-05 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_apps', '0002_auto_20200805_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='LoanApplication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan_apps.LoanApplication'),
        ),
    ]
