# Generated by Django 3.0.3 on 2020-08-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_apps', '0004_auto_20200805_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='business',
            name='SelfReportedCashFlow',
        ),
        migrations.AddField(
            model_name='address',
            name='Business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan_apps.Business'),
        ),
        migrations.AddField(
            model_name='selfreportedcashflow',
            name='Business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan_apps.Business'),
        ),
    ]
