# Generated by Django 3.0.3 on 2020-08-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_apps', '0005_auto_20200805_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Business',
        ),
        migrations.RemoveField(
            model_name='selfreportedcashflow',
            name='Business',
        ),
        migrations.AddField(
            model_name='business',
            name='Address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan_apps.Address'),
        ),
        migrations.AddField(
            model_name='business',
            name='SelfReportedCashFlow',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan_apps.SelfReportedCashFlow'),
        ),
    ]
