# Generated by Django 3.0.3 on 2020-08-05 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_apps', '0007_auto_20200805_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Business',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='loan_apps.Business'),
        ),
        migrations.AlterField(
            model_name='selfreportedcashflow',
            name='Business',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SelfReportedCashFlow', to='loan_apps.Business'),
        ),
    ]
