# Generated by Django 3.0.3 on 2020-08-05 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_apps', '0008_auto_20200805_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestheader',
            old_name='CFRequestID',
            new_name='CFRequestId',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='HomeAddress',
        ),
        migrations.AddField(
            model_name='address',
            name='Owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HomeAddress', to='loan_apps.Owner'),
        ),
        migrations.AlterField(
            model_name='address',
            name='Address2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='LoanApplication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan_apps.LoanApplication'),
        ),
        migrations.AlterField(
            model_name='cfapplicationdata',
            name='LoanApplication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan_apps.LoanApplication'),
        ),
        migrations.AlterField(
            model_name='requestheader',
            name='CFApiPassword',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requestheader',
            name='CFApiUserId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requestheader',
            name='LoanApplication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan_apps.LoanApplication'),
        ),
    ]
