# Generated by Django 3.0.3 on 2020-08-05 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_apps', '0009_auto_20200805_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='LoanApplication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Business', to='loan_apps.LoanApplication'),
        ),
        migrations.AlterField(
            model_name='cfapplicationdata',
            name='LoanApplication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CFApplicationData', to='loan_apps.LoanApplication'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='owner',
            name='LoanApplication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owners', to='loan_apps.LoanApplication'),
        ),
        migrations.AlterField(
            model_name='requestheader',
            name='LoanApplication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestHeader', to='loan_apps.LoanApplication'),
        ),
    ]
